//
//  DrawView.m
//  RSSchool_T8
//
//  Created by rasul on 7/17/21.
//

#import "DrawView.h"
#import "UIColor+Extension.h"

@implementation DrawView

- (instancetype)init {
  self = [super init];
  if (self) {
    self.backgroundColor = UIColor.whiteColor;
    self.layer.backgroundColor = UIColor.whiteColor.CGColor;
    self.layer.cornerRadius = 8.0;
    self.layer.shadowRadius = 4.0;
    self.layer.shadowOpacity = 0.25;
    self.layer.shadowOffset = CGSizeZero;
    self.layer.shadowColor = UIColor.chillSky.CGColor;
    
    _progress = 1.0/(60.0*1.0);
    _type = DrawHead;
  }
  return self;
}

- (void)drawRect:(CGRect)rect {
  switch (_type) {
    case DrawPlanet:
      [self setDefault];
      self.shapeLayer.path = [self drawPlanet].CGPath;
      break;
    case DrawHead:
      [self setDefault];
      self.shapeLayer.path = [self drawHead:@[UIColor.redColor, UIColor.greenColor, UIColor.blueColor]].CGPath;
      break;
    case DrawTree:
      [self setDefault];
      self.shapeLayer.path = [self drawTree].CGPath;
      break;
    case DrawLandscape:
      [self setDefault];
      self.shapeLayer.path = [self drawLandscape].CGPath;
      break;
      
    default:
      break;
  }
}

-(void)setDefault {
  [self.shapeLayer removeFromSuperlayer];
  self.shapeLayer = [self createClearLayer];
  [self.layer addSublayer: self.shapeLayer];
}

-(CAShapeLayer *)createClearLayer {
  CAShapeLayer *newLayer = [[CAShapeLayer alloc] init];
  newLayer.strokeStart = 0.0;
  newLayer.strokeEnd = 0.0;
  [newLayer setFillColor:[UIColor whiteColor].CGColor];
  [newLayer setStrokeColor:[UIColor blackColor].CGColor];
  return newLayer;
}

-(void)changeStrokeEnd {
  self.shapeLayer.strokeEnd += self.progress;
}

-(UIBezierPath *)drawPlanet {
  // This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
  // http://www.paintcodeapp.com
  
  //// Color Declarations
  UIColor* fillColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
  UIColor* strokeColor = [UIColor colorWithRed: 0 green: 0 blue: 0 alpha: 1];
  
  //// planet-frame.svg Group
  
  //// Rectangle Drawing
  UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(0, 0, 300, 300)];
  [fillColor setFill];
  [rectanglePath fill];
  
  
  //// Bezier Drawing
  UIBezierPath* bezierPath = [UIBezierPath bezierPath];
  [bezierPath moveToPoint: CGPointMake(71.03, 153.53)];
  [bezierPath addLineToPoint: CGPointMake(63.09, 157.06)];
  [bezierPath addLineToPoint: CGPointMake(55.15, 163.24)];
  [bezierPath addLineToPoint: CGPointMake(47.65, 170.29)];
  [bezierPath addLineToPoint: CGPointMake(42.35, 177.35)];
  [bezierPath addLineToPoint: CGPointMake(40.59, 184.41)];
  [bezierPath addLineToPoint: CGPointMake(41.47, 191.47)];
  [bezierPath addLineToPoint: CGPointMake(45, 197.21)];
  [bezierPath addLineToPoint: CGPointMake(51.18, 202.06)];
  [bezierPath addLineToPoint: CGPointMake(60.44, 206.03)];
  [bezierPath addLineToPoint: CGPointMake(70.15, 208.24)];
  [bezierPath addLineToPoint: CGPointMake(80.29, 209.12)];
  [bezierPath addLineToPoint: CGPointMake(90, 209.56)];
  [bezierPath addLineToPoint: CGPointMake(95.74, 209.38)];
  [bezierPath moveToPoint: CGPointMake(71.03, 153.53)];
  [bezierPath addLineToPoint: CGPointMake(71.47, 147.35)];
  [bezierPath addLineToPoint: CGPointMake(73.68, 136.32)];
  [bezierPath addLineToPoint: CGPointMake(76.76, 127.06)];
  [bezierPath addLineToPoint: CGPointMake(80.74, 116.91)];
  [bezierPath addLineToPoint: CGPointMake(85.59, 109.41)];
  [bezierPath addLineToPoint: CGPointMake(91.76, 101.03)];
  [bezierPath addLineToPoint: CGPointMake(98.82, 94.41)];
  [bezierPath addLineToPoint: CGPointMake(105.88, 89.56)];
  [bezierPath addLineToPoint: CGPointMake(113.38, 85.15)];
  [bezierPath addCurveToPoint: CGPointMake(123.53, 80.74) controlPoint1: CGPointMake(116.62, 83.82) controlPoint2: CGPointMake(123.18, 81.09)];
  [bezierPath addCurveToPoint: CGPointMake(133.24, 77.65) controlPoint1: CGPointMake(123.88, 80.38) controlPoint2: CGPointMake(130.15, 78.53)];
  [bezierPath addLineToPoint: CGPointMake(147.79, 76.32)];
  [bezierPath addLineToPoint: CGPointMake(160.15, 77.21)];
  [bezierPath addLineToPoint: CGPointMake(172.5, 79.41)];
  [bezierPath addLineToPoint: CGPointMake(183.53, 83.82)];
  [bezierPath addLineToPoint: CGPointMake(194.12, 90.44)];
  [bezierPath addLineToPoint: CGPointMake(201.62, 96.62)];
  [bezierPath addLineToPoint: CGPointMake(207.79, 102.79)];
  [bezierPath addLineToPoint: CGPointMake(213.09, 108.97)];
  [bezierPath moveToPoint: CGPointMake(71.03, 153.53)];
  [bezierPath addLineToPoint: CGPointMake(71.03, 159.26)];
  [bezierPath addLineToPoint: CGPointMake(71.91, 165.88)];
  [bezierPath moveToPoint: CGPointMake(213.09, 108.97)];
  [bezierPath addLineToPoint: CGPointMake(221.03, 107.65)];
  [bezierPath addLineToPoint: CGPointMake(231.62, 107.21)];
  [bezierPath addLineToPoint: CGPointMake(241.76, 108.53)];
  [bezierPath addLineToPoint: CGPointMake(251.03, 112.06)];
  [bezierPath addLineToPoint: CGPointMake(257.21, 116.91)];
  [bezierPath addLineToPoint: CGPointMake(259.41, 123.53)];
  [bezierPath addLineToPoint: CGPointMake(258.97, 131.47)];
  [bezierPath addLineToPoint: CGPointMake(255.88, 138.97)];
  [bezierPath addLineToPoint: CGPointMake(246.62, 150.88)];
  [bezierPath addLineToPoint: CGPointMake(239.12, 158.38)];
  [bezierPath addLineToPoint: CGPointMake(227.65, 167.21)];
  [bezierPath addLineToPoint: CGPointMake(224.71, 168.97)];
  [bezierPath moveToPoint: CGPointMake(213.09, 108.97)];
  [bezierPath addLineToPoint: CGPointMake(216.18, 113.38)];
  [bezierPath addLineToPoint: CGPointMake(218.82, 119.12)];
  [bezierPath moveToPoint: CGPointMake(71.91, 165.88)];
  [bezierPath addLineToPoint: CGPointMake(68.38, 168.09)];
  [bezierPath addLineToPoint: CGPointMake(65.29, 172.06)];
  [bezierPath addLineToPoint: CGPointMake(63.97, 176.47)];
  [bezierPath addLineToPoint: CGPointMake(64.41, 180.88)];
  [bezierPath addLineToPoint: CGPointMake(66.62, 184.41)];
  [bezierPath addLineToPoint: CGPointMake(71.03, 187.06)];
  [bezierPath addLineToPoint: CGPointMake(77.65, 189.71)];
  [bezierPath addLineToPoint: CGPointMake(79.85, 190.12)];
  [bezierPath moveToPoint: CGPointMake(71.91, 165.88)];
  [bezierPath addLineToPoint: CGPointMake(74.12, 173.38)];
  [bezierPath addLineToPoint: CGPointMake(76.32, 180.88)];
  [bezierPath addLineToPoint: CGPointMake(79.85, 190.12)];
  [bezierPath moveToPoint: CGPointMake(218.82, 119.12)];
  [bezierPath addLineToPoint: CGPointMake(224.56, 119.12)];
  [bezierPath addLineToPoint: CGPointMake(231.62, 121.76)];
  [bezierPath addLineToPoint: CGPointMake(234.26, 125.29)];
  [bezierPath addLineToPoint: CGPointMake(234.71, 130.59)];
  [bezierPath addLineToPoint: CGPointMake(233.38, 135.44)];
  [bezierPath addLineToPoint: CGPointMake(229.85, 140.29)];
  [bezierPath addLineToPoint: CGPointMake(226.62, 143.82)];
  [bezierPath moveToPoint: CGPointMake(218.82, 119.12)];
  [bezierPath addLineToPoint: CGPointMake(221.47, 125.29)];
  [bezierPath addLineToPoint: CGPointMake(224.71, 135.44)];
  [bezierPath addLineToPoint: CGPointMake(226.62, 143.82)];
  [bezierPath moveToPoint: CGPointMake(95.74, 209.38)];
  [bezierPath addLineToPoint: CGPointMake(104.56, 209.12)];
  [bezierPath addLineToPoint: CGPointMake(123.09, 206.91)];
  [bezierPath addLineToPoint: CGPointMake(138.53, 203.82)];
  [bezierPath addLineToPoint: CGPointMake(152.21, 200.29)];
  [bezierPath addLineToPoint: CGPointMake(169.41, 195)];
  [bezierPath addLineToPoint: CGPointMake(186.62, 188.38)];
  [bezierPath addLineToPoint: CGPointMake(200.29, 182.21)];
  [bezierPath addLineToPoint: CGPointMake(214.41, 175.15)];
  [bezierPath addLineToPoint: CGPointMake(224.71, 168.97)];
  [bezierPath moveToPoint: CGPointMake(95.74, 209.38)];
  [bezierPath addLineToPoint: CGPointMake(100.15, 214.41)];
  [bezierPath addLineToPoint: CGPointMake(107.21, 219.71)];
  [bezierPath addLineToPoint: CGPointMake(115.15, 223.68)];
  [bezierPath addLineToPoint: CGPointMake(123.09, 226.76)];
  [bezierPath addLineToPoint: CGPointMake(132.79, 229.85)];
  [bezierPath addLineToPoint: CGPointMake(143.82, 231.62)];
  [bezierPath addLineToPoint: CGPointMake(154.41, 231.62)];
  [bezierPath addLineToPoint: CGPointMake(164.12, 230.74)];
  [bezierPath addLineToPoint: CGPointMake(172.5, 228.53)];
  [bezierPath addLineToPoint: CGPointMake(179.12, 225.88)];
  [bezierPath addLineToPoint: CGPointMake(187.5, 221.91)];
  [bezierPath addLineToPoint: CGPointMake(194.12, 217.5)];
  [bezierPath addLineToPoint: CGPointMake(199.41, 213.53)];
  [bezierPath addLineToPoint: CGPointMake(206.47, 206.03)];
  [bezierPath addLineToPoint: CGPointMake(213.53, 197.21)];
  [bezierPath addLineToPoint: CGPointMake(218.38, 188.82)];
  [bezierPath addLineToPoint: CGPointMake(222.79, 178.24)];
  [bezierPath addLineToPoint: CGPointMake(224.71, 168.97)];
  [bezierPath moveToPoint: CGPointMake(226.62, 143.82)];
  [bezierPath addLineToPoint: CGPointMake(225, 145.59)];
  [bezierPath addLineToPoint: CGPointMake(220.59, 150)];
  [bezierPath addLineToPoint: CGPointMake(215.29, 153.97)];
  [bezierPath addLineToPoint: CGPointMake(208.68, 158.38)];
  [bezierPath addLineToPoint: CGPointMake(202.5, 162.35)];
  [bezierPath addLineToPoint: CGPointMake(196.32, 165.88)];
  [bezierPath addLineToPoint: CGPointMake(190.15, 168.97)];
  [bezierPath addLineToPoint: CGPointMake(182.21, 172.94)];
  [bezierPath addLineToPoint: CGPointMake(172.06, 177.35)];
  [bezierPath addLineToPoint: CGPointMake(161.91, 180.88)];
  [bezierPath addLineToPoint: CGPointMake(151.32, 183.97)];
  [bezierPath addLineToPoint: CGPointMake(141.18, 186.62)];
  [bezierPath addLineToPoint: CGPointMake(130.59, 188.82)];
  [bezierPath addLineToPoint: CGPointMake(120, 190.59)];
  [bezierPath addLineToPoint: CGPointMake(109.41, 191.47)];
  [bezierPath addLineToPoint: CGPointMake(99.26, 191.91)];
  [bezierPath addLineToPoint: CGPointMake(91.32, 191.47)];
  [bezierPath addLineToPoint: CGPointMake(84.71, 191.03)];
  [bezierPath addLineToPoint: CGPointMake(79.85, 190.12)];
  [strokeColor setStroke];
  bezierPath.lineWidth = 1;
  bezierPath.miterLimit = 4;
  bezierPath.lineCapStyle = kCGLineCapRound;
  
  
  //// Bezier 2 Drawing
  UIBezierPath* bezier2Path = [UIBezierPath bezierPath];
  [bezier2Path moveToPoint: CGPointMake(155.29, 118.68)];
  [bezier2Path addLineToPoint: CGPointMake(160.59, 116.03)];
  [bezier2Path addLineToPoint: CGPointMake(168.97, 111.18)];
  [bezier2Path addLineToPoint: CGPointMake(177.35, 105)];
  [bezier2Path addLineToPoint: CGPointMake(183.09, 98.82)];
  [bezier2Path addLineToPoint: CGPointMake(186.62, 92.65)];
  [bezier2Path addLineToPoint: CGPointMake(188.82, 87.35)];
  [bezier2Path moveToPoint: CGPointMake(114.26, 99.71)];
  [bezier2Path addLineToPoint: CGPointMake(108.09, 99.26)];
  [bezier2Path addLineToPoint: CGPointMake(102.79, 97.5)];
  [bezier2Path addLineToPoint: CGPointMake(98.38, 94.85)];
  [bezier2Path moveToPoint: CGPointMake(123.53, 98.38)];
  [bezier2Path addLineToPoint: CGPointMake(130.15, 96.62)];
  [bezier2Path addLineToPoint: CGPointMake(137.21, 94.41)];
  [bezier2Path addLineToPoint: CGPointMake(144.26, 90.44)];
  [bezier2Path addCurveToPoint: CGPointMake(150.88, 85.59) controlPoint1: CGPointMake(146.32, 88.97) controlPoint2: CGPointMake(150.53, 85.94)];
  [bezier2Path addCurveToPoint: CGPointMake(154.85, 81.18) controlPoint1: CGPointMake(151.24, 85.24) controlPoint2: CGPointMake(153.68, 82.5)];
  [bezier2Path addLineToPoint: CGPointMake(156.62, 77.21)];
  [bezier2Path moveToPoint: CGPointMake(103.68, 113.38)];
  [bezier2Path addLineToPoint: CGPointMake(107.65, 114.26)];
  [bezier2Path addLineToPoint: CGPointMake(114.26, 114.26)];
  [bezier2Path addLineToPoint: CGPointMake(121.32, 113.38)];
  [bezier2Path addLineToPoint: CGPointMake(127.5, 112.06)];
  [bezier2Path addLineToPoint: CGPointMake(135, 110.29)];
  [bezier2Path moveToPoint: CGPointMake(108.53, 130.59)];
  [bezier2Path addCurveToPoint: CGPointMake(112.06, 130.15) controlPoint1: CGPointMake(108.88, 130.59) controlPoint2: CGPointMake(111.03, 130.29)];
  [bezier2Path addLineToPoint: CGPointMake(116.03, 129.71)];
  [bezier2Path addLineToPoint: CGPointMake(119.56, 128.82)];
  [bezier2Path moveToPoint: CGPointMake(101.03, 130.15)];
  [bezier2Path addLineToPoint: CGPointMake(94.41, 129.71)];
  [bezier2Path addLineToPoint: CGPointMake(88.24, 127.5)];
  [bezier2Path addCurveToPoint: CGPointMake(82.5, 124.85) controlPoint1: CGPointMake(86.47, 126.62) controlPoint2: CGPointMake(82.85, 124.85)];
  [bezier2Path addCurveToPoint: CGPointMake(78.53, 122.65) controlPoint1: CGPointMake(82.15, 124.85) controlPoint2: CGPointMake(79.71, 123.38)];
  [bezier2Path moveToPoint: CGPointMake(93.97, 164.56)];
  [bezier2Path addLineToPoint: CGPointMake(86.91, 163.24)];
  [bezier2Path addLineToPoint: CGPointMake(78.97, 160.15)];
  [bezier2Path addLineToPoint: CGPointMake(71.03, 155.29)];
  [bezier2Path moveToPoint: CGPointMake(111.62, 164.56)];
  [bezier2Path addLineToPoint: CGPointMake(116.47, 164.56)];
  [bezier2Path addLineToPoint: CGPointMake(120.44, 164.12)];
  [bezier2Path addLineToPoint: CGPointMake(128.38, 162.79)];
  [bezier2Path addLineToPoint: CGPointMake(137.65, 160.59)];
  [bezier2Path addLineToPoint: CGPointMake(146.03, 158.38)];
  [bezier2Path addLineToPoint: CGPointMake(154.41, 155.74)];
  [bezier2Path addLineToPoint: CGPointMake(162.79, 153.09)];
  [bezier2Path addLineToPoint: CGPointMake(171.62, 149.12)];
  [bezier2Path addLineToPoint: CGPointMake(180, 145.15)];
  [bezier2Path addLineToPoint: CGPointMake(187.06, 140.74)];
  [bezier2Path addLineToPoint: CGPointMake(192.35, 137.21)];
  [bezier2Path addLineToPoint: CGPointMake(197.21, 134.12)];
  [bezier2Path moveToPoint: CGPointMake(204.71, 127.06)];
  [bezier2Path addLineToPoint: CGPointMake(208.24, 122.65)];
  [bezier2Path addLineToPoint: CGPointMake(211.32, 117.35)];
  [bezier2Path addLineToPoint: CGPointMake(213.97, 110.74)];
  [bezier2Path moveToPoint: CGPointMake(128.38, 145.59)];
  [bezier2Path addLineToPoint: CGPointMake(135.44, 143.82)];
  [bezier2Path addLineToPoint: CGPointMake(146.91, 140.29)];
  [bezier2Path addLineToPoint: CGPointMake(154.41, 137.65)];
  [bezier2Path addLineToPoint: CGPointMake(162.35, 134.12)];
  [bezier2Path addLineToPoint: CGPointMake(168.97, 131.03)];
  [bezier2Path addLineToPoint: CGPointMake(174.71, 127.94)];
  [bezier2Path moveToPoint: CGPointMake(93.97, 180)];
  [bezier2Path addLineToPoint: CGPointMake(100.15, 180.44)];
  [bezier2Path addLineToPoint: CGPointMake(106.76, 180.44)];
  [bezier2Path addLineToPoint: CGPointMake(113.82, 179.56)];
  [bezier2Path moveToPoint: CGPointMake(185.74, 158.38)];
  [bezier2Path addLineToPoint: CGPointMake(191.03, 156.62)];
  [bezier2Path addLineToPoint: CGPointMake(197.65, 152.65)];
  [bezier2Path addLineToPoint: CGPointMake(205.59, 146.47)];
  [bezier2Path addLineToPoint: CGPointMake(210.88, 142.5)];
  [bezier2Path addLineToPoint: CGPointMake(214.41, 138.53)];
  [bezier2Path moveToPoint: CGPointMake(165, 206.03)];
  [bezier2Path addLineToPoint: CGPointMake(168.97, 205.15)];
  [bezier2Path addLineToPoint: CGPointMake(176.91, 202.06)];
  [bezier2Path addLineToPoint: CGPointMake(183.97, 198.97)];
  [bezier2Path addLineToPoint: CGPointMake(189.71, 196.32)];
  [bezier2Path addLineToPoint: CGPointMake(195, 193.68)];
  [bezier2Path addLineToPoint: CGPointMake(197.21, 191.03)];
  [bezier2Path moveToPoint: CGPointMake(201.62, 202.06)];
  [bezier2Path addLineToPoint: CGPointMake(206.91, 198.97)];
  [bezier2Path addLineToPoint: CGPointMake(211.76, 195.44)];
  [bezier2Path addLineToPoint: CGPointMake(218.38, 188.82)];
  [bezier2Path moveToPoint: CGPointMake(192.35, 207.35)];
  [bezier2Path addLineToPoint: CGPointMake(185.74, 210.44)];
  [bezier2Path addLineToPoint: CGPointMake(176.47, 213.97)];
  [bezier2Path addLineToPoint: CGPointMake(167.65, 217.06)];
  [bezier2Path addLineToPoint: CGPointMake(157.94, 219.71)];
  [bezier2Path addLineToPoint: CGPointMake(148.68, 221.91)];
  [bezier2Path addLineToPoint: CGPointMake(136.32, 223.24)];
  [bezier2Path addLineToPoint: CGPointMake(124.41, 223.68)];
  [bezier2Path addLineToPoint: CGPointMake(114.26, 223.24)];
  [strokeColor setStroke];
  bezier2Path.lineWidth = 1;
  bezier2Path.miterLimit = 4;
  bezier2Path.lineCapStyle = kCGLineCapRound;
  
  
  //// Bezier 3 Drawing
  UIBezierPath* bezier3Path = [UIBezierPath bezierPath];
  [bezier3Path moveToPoint: CGPointMake(240.44, 177.35)];
  [bezier3Path addLineToPoint: CGPointMake(244.85, 174.26)];
  [bezier3Path addLineToPoint: CGPointMake(251.03, 174.71)];
  [bezier3Path addLineToPoint: CGPointMake(255, 177.79)];
  [bezier3Path addLineToPoint: CGPointMake(256.32, 182.21)];
  [bezier3Path addLineToPoint: CGPointMake(255.44, 186.18)];
  [bezier3Path addLineToPoint: CGPointMake(252.79, 190.15)];
  [bezier3Path addLineToPoint: CGPointMake(248.38, 191.47)];
  [bezier3Path addLineToPoint: CGPointMake(243.09, 190.59)];
  [bezier3Path addLineToPoint: CGPointMake(239.56, 187.06)];
  [bezier3Path addLineToPoint: CGPointMake(238.24, 182.65)];
  [bezier3Path addLineToPoint: CGPointMake(240.44, 177.35)];
  [bezier3Path closePath];
  [strokeColor setStroke];
  bezier3Path.lineWidth = 1;
  bezier3Path.miterLimit = 4;
  bezier3Path.lineCapStyle = kCGLineCapRound;
  
  
  //// Bezier 4 Drawing
  UIBezierPath* bezier4Path = [UIBezierPath bezierPath];
  [bezier4Path moveToPoint: CGPointMake(229.41, 203.82)];
  [bezier4Path addLineToPoint: CGPointMake(231.18, 202.06)];
  [bezier4Path addLineToPoint: CGPointMake(233.38, 202.06)];
  [bezier4Path addLineToPoint: CGPointMake(235.15, 203.38)];
  [bezier4Path addLineToPoint: CGPointMake(235.59, 205.59)];
  [bezier4Path addLineToPoint: CGPointMake(234.71, 207.35)];
  [bezier4Path addLineToPoint: CGPointMake(232.5, 208.24)];
  [bezier4Path addLineToPoint: CGPointMake(230.29, 207.79)];
  [bezier4Path addLineToPoint: CGPointMake(228.97, 206.03)];
  [bezier4Path addLineToPoint: CGPointMake(229.41, 203.82)];
  [bezier4Path closePath];
  [strokeColor setStroke];
  bezier4Path.lineWidth = 1;
  bezier4Path.miterLimit = 4;
  bezier4Path.lineCapStyle = kCGLineCapRound;
  
  
  //// Bezier 5 Drawing
  UIBezierPath* bezier5Path = [UIBezierPath bezierPath];
  [bezier5Path moveToPoint: CGPointMake(83.38, 231.18)];
  [bezier5Path addLineToPoint: CGPointMake(85.15, 230.29)];
  [bezier5Path addLineToPoint: CGPointMake(87.79, 231.18)];
  [bezier5Path addCurveToPoint: CGPointMake(89.12, 233.38) controlPoint1: CGPointMake(88.24, 231.76) controlPoint2: CGPointMake(89.12, 233.03)];
  [bezier5Path addCurveToPoint: CGPointMake(89.12, 236.03) controlPoint1: CGPointMake(89.12, 233.74) controlPoint2: CGPointMake(89.27, 235.44)];
  [bezier5Path addLineToPoint: CGPointMake(86.91, 237.35)];
  [bezier5Path addLineToPoint: CGPointMake(83.82, 237.35)];
  [bezier5Path addLineToPoint: CGPointMake(82.5, 235.59)];
  [bezier5Path addLineToPoint: CGPointMake(82.06, 233.38)];
  [bezier5Path addLineToPoint: CGPointMake(83.38, 231.18)];
  [bezier5Path closePath];
  [strokeColor setStroke];
  bezier5Path.lineWidth = 1;
  bezier5Path.miterLimit = 4;
  bezier5Path.lineCapStyle = kCGLineCapRound;
  
  
  //// Bezier 6 Drawing
  UIBezierPath* bezier6Path = [UIBezierPath bezierPath];
  [bezier6Path moveToPoint: CGPointMake(48.97, 85.15)];
  [bezier6Path addCurveToPoint: CGPointMake(54.26, 81.18) controlPoint1: CGPointMake(50.59, 83.82) controlPoint2: CGPointMake(53.91, 81.18)];
  [bezier6Path addLineToPoint: CGPointMake(60, 80.29)];
  [bezier6Path addLineToPoint: CGPointMake(65.74, 82.06)];
  [bezier6Path addLineToPoint: CGPointMake(71.03, 88.24)];
  [bezier6Path addLineToPoint: CGPointMake(71.47, 96.62)];
  [bezier6Path addLineToPoint: CGPointMake(67.94, 103.24)];
  [bezier6Path addLineToPoint: CGPointMake(60.44, 106.76)];
  [bezier6Path addLineToPoint: CGPointMake(52.5, 105)];
  [bezier6Path addLineToPoint: CGPointMake(47.21, 101.03)];
  [bezier6Path addLineToPoint: CGPointMake(45.44, 93.09)];
  [bezier6Path addLineToPoint: CGPointMake(48.97, 85.15)];
  [bezier6Path closePath];
  [strokeColor setStroke];
  bezier6Path.lineWidth = 1;
  bezier6Path.miterLimit = 4;
  bezier6Path.lineCapStyle = kCGLineCapRound;
  
  
  //// Bezier 7 Drawing
  UIBezierPath* bezier7Path = [UIBezierPath bezierPath];
  [bezier7Path moveToPoint: CGPointMake(209.12, 62.65)];
  [bezier7Path addCurveToPoint: CGPointMake(213.97, 61.76) controlPoint1: CGPointMake(210, 62.35) controlPoint2: CGPointMake(213.62, 61.76)];
  [bezier7Path addLineToPoint: CGPointMake(217.94, 64.41)];
  [bezier7Path addLineToPoint: CGPointMake(218.38, 68.82)];
  [bezier7Path addLineToPoint: CGPointMake(216.62, 72.35)];
  [bezier7Path addLineToPoint: CGPointMake(212.21, 73.68)];
  [bezier7Path addLineToPoint: CGPointMake(207.79, 71.47)];
  [bezier7Path addLineToPoint: CGPointMake(206.47, 66.62)];
  [bezier7Path addLineToPoint: CGPointMake(209.12, 62.65)];
  [bezier7Path closePath];
  [strokeColor setStroke];
  bezier7Path.lineWidth = 1;
  bezier7Path.miterLimit = 4;
  bezier7Path.lineCapStyle = kCGLineCapRound;
  
  UIBezierPath *resultPath = [[UIBezierPath alloc] init];
  [resultPath appendPath:bezierPath];
  [resultPath appendPath:bezier2Path];
  [resultPath appendPath:bezier3Path];
  [resultPath appendPath:bezier4Path];
  [resultPath appendPath:bezier5Path];
  [resultPath appendPath:bezier6Path];
  [resultPath appendPath:bezier7Path];
  
  return resultPath;
}

-(UIBezierPath *)drawHead: (NSArray<UIColor *>*) color {
  // This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
  // http://www.paintcodeapp.com
  
  //// Color Declarations
  UIColor* fillColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
  
  //// head-frame.svg Group
  
  //// Rectangle Drawing
  UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(5, 5, 290, 290)];
  [fillColor setFill];
  [rectanglePath fill];
  
  
  //// Bezier Drawing
  UIBezierPath* bezierPath = [UIBezierPath bezierPath];
  [bezierPath moveToPoint: CGPointMake(71.91, 43.24)];
  [bezierPath addLineToPoint: CGPointMake(85.59, 96.18)];
  [bezierPath addLineToPoint: CGPointMake(96.18, 116.47)];
  [bezierPath addLineToPoint: CGPointMake(111.62, 133.68)];
  [bezierPath addLineToPoint: CGPointMake(135.44, 153.53)];
  [bezierPath addLineToPoint: CGPointMake(156.18, 158.38)];
  [bezierPath addLineToPoint: CGPointMake(187.94, 142.94)];
  [bezierPath addLineToPoint: CGPointMake(211.76, 116.47)];
  [bezierPath addLineToPoint: CGPointMake(219.26, 105.88)];
  [bezierPath addLineToPoint: CGPointMake(219.26, 86.03)];
  [bezierPath addLineToPoint: CGPointMake(221.03, 62.21)];
  [bezierPath addLineToPoint: CGPointMake(210.44, 53.38)];
  [bezierPath addLineToPoint: CGPointMake(195.88, 56.03)];
  [bezierPath addLineToPoint: CGPointMake(186.18, 71.03)];
  [bezierPath addLineToPoint: CGPointMake(184.41, 91.32)];
  [bezierPath addLineToPoint: CGPointMake(187.94, 102.35)];
  bezierPath.lineWidth = 1;
  bezierPath.miterLimit = 4;
  [UIColor.redColor setFill];
  bezierPath.lineCapStyle = kCGLineCapRound;
  
  //// Bezier 2 Drawing
  UIBezierPath* bezier2Path = [UIBezierPath bezierPath];
  [bezier2Path moveToPoint: CGPointMake(180, 105.88)];
  [bezier2Path addLineToPoint: CGPointMake(172.5, 104.56)];
  [bezier2Path addLineToPoint: CGPointMake(164.12, 106.32)];
  [bezier2Path addLineToPoint: CGPointMake(157.06, 107.21)];
  [bezier2Path addLineToPoint: CGPointMake(148.68, 106.32)];
  [bezier2Path addLineToPoint: CGPointMake(141.18, 105)];
  [bezier2Path addLineToPoint: CGPointMake(135.44, 104.56)];
  [bezier2Path addLineToPoint: CGPointMake(128.82, 105.88)];
  [bezier2Path addLineToPoint: CGPointMake(124.85, 107.65)];
  [bezier2Path addLineToPoint: CGPointMake(130.15, 109.85)];
  [bezier2Path addLineToPoint: CGPointMake(134.12, 112.94)];
  [bezier2Path addLineToPoint: CGPointMake(138.09, 117.35)];
  [bezier2Path addLineToPoint: CGPointMake(143.38, 119.56)];
  [bezier2Path addLineToPoint: CGPointMake(150, 120.44)];
  [bezier2Path addLineToPoint: CGPointMake(156.18, 119.56)];
  [bezier2Path addLineToPoint: CGPointMake(162.79, 120.44)];
  [bezier2Path addLineToPoint: CGPointMake(168.09, 119.56)];
  [bezier2Path addLineToPoint: CGPointMake(173.82, 116.03)];
  [bezier2Path addLineToPoint: CGPointMake(180, 108.97)];
  [bezier2Path addLineToPoint: CGPointMake(183.97, 103.68)];
  [bezier2Path addLineToPoint: CGPointMake(176.91, 102.79)];
  [bezier2Path addLineToPoint: CGPointMake(168.97, 101.91)];
  [bezier2Path addLineToPoint: CGPointMake(161.03, 100.15)];
  [bezier2Path addLineToPoint: CGPointMake(153.53, 99.71)];
  [bezier2Path addLineToPoint: CGPointMake(144.71, 101.03)];
  [bezier2Path addLineToPoint: CGPointMake(136.76, 102.79)];
  [bezier2Path addLineToPoint: CGPointMake(127.94, 103.68)];
  [bezier2Path addLineToPoint: CGPointMake(121.76, 103.24)];
  [bezier2Path addLineToPoint: CGPointMake(130.15, 97.94)];
  [bezier2Path addLineToPoint: CGPointMake(138.09, 92.21)];
  [bezier2Path addLineToPoint: CGPointMake(143.38, 89.12)];
  [bezier2Path addLineToPoint: CGPointMake(147.79, 90.44)];
  [bezier2Path addLineToPoint: CGPointMake(152.65, 92.21)];
  [bezier2Path addLineToPoint: CGPointMake(158.38, 91.32)];
  [bezier2Path addLineToPoint: CGPointMake(164.12, 90.44)];
  [bezier2Path addLineToPoint: CGPointMake(168.97, 90.44)];
  [bezier2Path addLineToPoint: CGPointMake(171.62, 92.21)];
  [bezier2Path addLineToPoint: CGPointMake(176.03, 96.62)];
  [bezier2Path addLineToPoint: CGPointMake(182.65, 100.59)];
  bezier2Path.lineWidth = 1;
  bezier2Path.miterLimit = 4;
  [color[1] setFill];
  bezier2Path.lineCapStyle = kCGLineCapRound;
  
  //// Bezier 3 Drawing
  UIBezierPath* bezier3Path = [UIBezierPath bezierPath];
  [bezier3Path moveToPoint: CGPointMake(184.85, 108.09)];
  [bezier3Path addLineToPoint: CGPointMake(188.82, 113.38)];
  [bezier3Path addLineToPoint: CGPointMake(191.03, 119.12)];
  [bezier3Path addLineToPoint: CGPointMake(187.94, 127.06)];
  [bezier3Path addLineToPoint: CGPointMake(181.76, 134.56)];
  [bezier3Path addLineToPoint: CGPointMake(173.82, 140.74)];
  [bezier3Path addLineToPoint: CGPointMake(165.44, 134.56)];
  [bezier3Path addLineToPoint: CGPointMake(156.18, 131.03)];
  [bezier3Path addLineToPoint: CGPointMake(147.79, 131.03)];
  [bezier3Path addLineToPoint: CGPointMake(137.21, 134.56)];
  [bezier3Path addLineToPoint: CGPointMake(130.15, 142.94)];
  [bezier3Path addLineToPoint: CGPointMake(124.41, 153.97)];
  [bezier3Path addLineToPoint: CGPointMake(114.26, 147.79)];
  [bezier3Path addLineToPoint: CGPointMake(107.21, 138.97)];
  [bezier3Path addLineToPoint: CGPointMake(99.71, 131.03)];
  [bezier3Path addLineToPoint: CGPointMake(99.71, 142.94)];
  [bezier3Path addLineToPoint: CGPointMake(99.71, 168.09)];
  [bezier3Path addLineToPoint: CGPointMake(99.71, 183.09)];
  [bezier3Path addLineToPoint: CGPointMake(93.53, 193.24)];
  [bezier3Path addLineToPoint: CGPointMake(83.38, 200.74)];
  [bezier3Path addLineToPoint: CGPointMake(73.68, 206.91)];
  [bezier3Path addLineToPoint: CGPointMake(89.12, 212.65)];
  [bezier3Path addLineToPoint: CGPointMake(101.03, 220.15)];
  [bezier3Path addLineToPoint: CGPointMake(110.29, 232.5)];
  [bezier3Path addLineToPoint: CGPointMake(122.65, 247.94)];
  [bezier3Path addLineToPoint: CGPointMake(139.41, 263.82)];
  [bezier3Path addLineToPoint: CGPointMake(156.18, 269.56)];
  [bezier3Path addLineToPoint: CGPointMake(168.53, 269.56)];
  [bezier3Path addLineToPoint: CGPointMake(181.76, 262.5)];
  [bezier3Path addLineToPoint: CGPointMake(193.68, 247.94)];
  [bezier3Path addLineToPoint: CGPointMake(202.5, 228.97)];
  [bezier3Path addLineToPoint: CGPointMake(210.88, 214.85)];
  [bezier3Path addLineToPoint: CGPointMake(223.68, 209.12)];
  [bezier3Path addLineToPoint: CGPointMake(226.76, 209.12)];
  [bezier3Path addLineToPoint: CGPointMake(221.03, 195.44)];
  [bezier3Path addLineToPoint: CGPointMake(212.65, 170.29)];
  [bezier3Path addLineToPoint: CGPointMake(210.88, 150)];
  [bezier3Path addLineToPoint: CGPointMake(210.88, 129.26)];
  [bezier3Path addLineToPoint: CGPointMake(204.71, 138.97)];
  [bezier3Path addLineToPoint: CGPointMake(197.65, 146.03)];
  [bezier3Path addLineToPoint: CGPointMake(191.03, 153.97)];
  [bezier3Path addLineToPoint: CGPointMake(176.47, 168.09)];
  [bezier3Path addLineToPoint: CGPointMake(167.65, 180.88)];
  [bezier3Path addLineToPoint: CGPointMake(160.15, 199.85)];
  [bezier3Path addLineToPoint: CGPointMake(157.5, 222.79)];
  [bezier3Path addLineToPoint: CGPointMake(157.5, 247.94)];
  [bezier3Path addLineToPoint: CGPointMake(157.5, 263.82)];
  bezier3Path.lineWidth = 1;
  [color[2] setFill];
  bezier3Path.miterLimit = 4;
  bezier3Path.lineCapStyle = kCGLineCapRound;
  
  
  UIBezierPath *resultPath = [[UIBezierPath alloc] init];
  [resultPath appendPath:bezierPath];
  [resultPath appendPath:bezier2Path];
  [resultPath appendPath:bezier3Path];
  
  return resultPath;
}

-(UIBezierPath *)drawTree {
  // This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
  // http://www.paintcodeapp.com
  
  //// Color Declarations
  UIColor* fillColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
  
  //// tree.svg Group
  
  //// Rectangle Drawing
  UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(0, 0, 300, 300)];
  [fillColor setFill];
  [rectanglePath fill];
  
  //// Bezier 2 Drawing
  UIBezierPath *bezierPath2 = [UIBezierPath bezierPath];
  
  [bezierPath2 moveToPoint:CGPointMake(233.19,85.76)];
  [bezierPath2 addCurveToPoint:CGPointMake(220.5,62) controlPoint1: CGPointMake(237,68.49) controlPoint2: CGPointMake(229.61,62)];
  [bezierPath2 addCurveToPoint:CGPointMake(215.97,62.55) controlPoint1: CGPointMake(218.93,62) controlPoint2: CGPointMake(217.41,62.19)];
  [bezierPath2 addCurveToPoint:CGPointMake(199.5,49) controlPoint1: CGPointMake(215.41,54.99) controlPoint2: CGPointMake(208.25,49)];
  [bezierPath2 addCurveToPoint:CGPointMake(191.6,50.77) controlPoint1: CGPointMake(196.64,49) controlPoint2: CGPointMake(193.94,49.64)];
  [bezierPath2 addCurveToPoint:CGPointMake(180.5,47) controlPoint1: CGPointMake(188.67,48.43) controlPoint2: CGPointMake(184.77,47)];
  [bezierPath2 addCurveToPoint:CGPointMake(175.97,47.55) controlPoint1: CGPointMake(178.93,47) controlPoint2: CGPointMake(177.41,47.19)];
  [bezierPath2 addCurveToPoint:CGPointMake(159.5,34) controlPoint1: CGPointMake(175.41,39.99) controlPoint2: CGPointMake(168.25,34)];
  [bezierPath2 addCurveToPoint:CGPointMake(145.59,40.7) controlPoint1: CGPointMake(153.65,34) controlPoint2: CGPointMake(148.52,36.67)];
  [bezierPath2 addCurveToPoint:CGPointMake(140.5,40) controlPoint1: CGPointMake(143.98,40.25) controlPoint2: CGPointMake(142.28,40)];
  [bezierPath2 addCurveToPoint:CGPointMake(130.81,42.77) controlPoint1: CGPointMake(136.88,40) controlPoint2: CGPointMake(133.53,41.03)];
  [bezierPath2 addCurveToPoint:CGPointMake(125.5,42) controlPoint1: CGPointMake(129.14,42.27) controlPoint2: CGPointMake(127.36,42)];
  [bezierPath2 addCurveToPoint:CGPointMake(111.59,48.7) controlPoint1: CGPointMake(119.65,42) controlPoint2: CGPointMake(114.52,44.67)];
  [bezierPath2 addCurveToPoint:CGPointMake(106.5,48) controlPoint1: CGPointMake(109.98,48.25) controlPoint2: CGPointMake(108.28,48)];
  [bezierPath2 addCurveToPoint:CGPointMake(90,62.5) controlPoint1: CGPointMake(97.39,48) controlPoint2: CGPointMake(90,54.49)];
  [bezierPath2 addCurveToPoint:CGPointMake(90.01,63.02) controlPoint1: CGPointMake(90,62.68) controlPoint2: CGPointMake(90,62.85)];
  [bezierPath2 addCurveToPoint:CGPointMake(88.59,64.7) controlPoint1: CGPointMake(89.49,63.55) controlPoint2: CGPointMake(89.02,64.11)];
  [bezierPath2 addCurveToPoint:CGPointMake(83.5,64) controlPoint1: CGPointMake(86.98,64.25) controlPoint2: CGPointMake(85.28,64)];
  [bezierPath2 addCurveToPoint:CGPointMake(67,78.5) controlPoint1: CGPointMake(74.39,64) controlPoint2: CGPointMake(67,70.49)];
  [bezierPath2 addCurveToPoint:CGPointMake(68.58,84.71) controlPoint1: CGPointMake(67,80.72) controlPoint2: CGPointMake(67.57,82.83)];
  [bezierPath2 addCurveToPoint:CGPointMake(66,92.5) controlPoint1: CGPointMake(66.95,86.96) controlPoint2: CGPointMake(66,89.63)];
  [bezierPath2 addCurveToPoint:CGPointMake(67.19,97.92) controlPoint1: CGPointMake(66,94.42) controlPoint2: CGPointMake(66.42,96.25)];
  [bezierPath2 addCurveToPoint:CGPointMake(64,106.5) controlPoint1: CGPointMake(65.19,100.33) controlPoint2: CGPointMake(64,103.29)];
  [bezierPath2 addCurveToPoint:CGPointMake(65.58,112.71) controlPoint1: CGPointMake(64,108.72) controlPoint2: CGPointMake(64.57,110.83)];
  [bezierPath2 addCurveToPoint:CGPointMake(63,120.5) controlPoint1: CGPointMake(63.95,114.96) controlPoint2: CGPointMake(63,117.63)];
  [bezierPath2 addCurveToPoint:CGPointMake(79.5,135) controlPoint1: CGPointMake(63,128.51) controlPoint2: CGPointMake(70.39,135)];
  [bezierPath2 addCurveToPoint:CGPointMake(81.68,134.88) controlPoint1: CGPointMake(80.24,135) controlPoint2: CGPointMake(80.96,134.96)];
  [bezierPath2 addCurveToPoint:CGPointMake(96.5,143) controlPoint1: CGPointMake(84.36,139.69) controlPoint2: CGPointMake(89.99,143)];
  [bezierPath2 addCurveToPoint:CGPointMake(104.35,141.26) controlPoint1: CGPointMake(99.34,143) controlPoint2: CGPointMake(102.02,142.37)];
  [bezierPath2 addCurveToPoint:CGPointMake(119.5,150) controlPoint1: CGPointMake(106.89,146.4) controlPoint2: CGPointMake(112.72,150)];
  [bezierPath2 addCurveToPoint:CGPointMake(121.68,149.88) controlPoint1: CGPointMake(120.24,150) controlPoint2: CGPointMake(120.96,149.96)];
  [bezierPath2 addCurveToPoint:CGPointMake(136.5,158) controlPoint1: CGPointMake(124.36,154.69) controlPoint2: CGPointMake(129.99,158)];
  [bezierPath2 addCurveToPoint:CGPointMake(145,155.93) controlPoint1: CGPointMake(139.61,158) controlPoint2: CGPointMake(142.52,157.24)];
  [bezierPath2 addCurveToPoint:CGPointMake(149.66,157.6) controlPoint1: CGPointMake(146.43,156.69) controlPoint2: CGPointMake(147.99,157.26)];
  [bezierPath2 addCurveToPoint:CGPointMake(162.5,163) controlPoint1: CGPointMake(152.68,160.9) controlPoint2: CGPointMake(157.31,163)];
  [bezierPath2 addCurveToPoint:CGPointMake(170.35,161.26) controlPoint1: CGPointMake(165.34,163) controlPoint2: CGPointMake(168.02,162.37)];
  [bezierPath2 addCurveToPoint:CGPointMake(185.5,170) controlPoint1: CGPointMake(172.89,166.4) controlPoint2: CGPointMake(178.72,170)];
  [bezierPath2 addCurveToPoint:CGPointMake(187.68,169.88) controlPoint1: CGPointMake(186.24,170) controlPoint2: CGPointMake(186.96,169.96)];
  [bezierPath2 addCurveToPoint:CGPointMake(202.5,178) controlPoint1: CGPointMake(190.36,174.69) controlPoint2: CGPointMake(195.99,178)];
  [bezierPath2 addCurveToPoint:CGPointMake(211,175.93) controlPoint1: CGPointMake(205.61,178) controlPoint2: CGPointMake(208.52,177.24)];
  [bezierPath2 addCurveToPoint:CGPointMake(219.5,178) controlPoint1: CGPointMake(213.48,177.24) controlPoint2: CGPointMake(216.39,178)];
  [bezierPath2 addCurveToPoint:CGPointMake(236,163.5) controlPoint1: CGPointMake(228.61,178) controlPoint2: CGPointMake(236,171.51)];
  [bezierPath2 addCurveToPoint:CGPointMake(235.99,162.99) controlPoint1: CGPointMake(236,163.33) controlPoint2: CGPointMake(236,163.16)];
  [bezierPath2 addCurveToPoint:CGPointMake(236.5,163) controlPoint1: CGPointMake(236.16,163) controlPoint2: CGPointMake(236.33,163)];
  [bezierPath2 addCurveToPoint:CGPointMake(245,160.93) controlPoint1: CGPointMake(239.61,163) controlPoint2: CGPointMake(242.52,162.24)];
  [bezierPath2 addCurveToPoint:CGPointMake(253.5,163) controlPoint1: CGPointMake(247.48,162.24) controlPoint2: CGPointMake(250.39,163)];
  [bezierPath2 addCurveToPoint:CGPointMake(270,148.5) controlPoint1: CGPointMake(262.61,163) controlPoint2: CGPointMake(270,156.51)];
  [bezierPath2 addCurveToPoint:CGPointMake(269.66,145.56) controlPoint1: CGPointMake(270,147.49) controlPoint2: CGPointMake(269.88,146.51)];
  [bezierPath2 addCurveToPoint:CGPointMake(277,133.5) controlPoint1: CGPointMake(274.09,142.96) controlPoint2: CGPointMake(277,138.53)];
  [bezierPath2 addCurveToPoint:CGPointMake(273.19,124.24) controlPoint1: CGPointMake(277,129.98) controlPoint2: CGPointMake(275.57,126.75)];
  [bezierPath2 addCurveToPoint:CGPointMake(280,112.5) controlPoint1: CGPointMake(277.32,121.6) controlPoint2: CGPointMake(280,117.33)];
  [bezierPath2 addCurveToPoint:CGPointMake(263.5,98) controlPoint1: CGPointMake(280,104.49) controlPoint2: CGPointMake(272.61,98)];
  [bezierPath2 addCurveToPoint:CGPointMake(258.96,98.55) controlPoint1: CGPointMake(261.93,98) controlPoint2: CGPointMake(260.41,98.19)];
  [bezierPath2 addCurveToPoint:CGPointMake(242.5,85) controlPoint1: CGPointMake(258.41,90.99) controlPoint2: CGPointMake(251.25,85)];
  [bezierPath2 addCurveToPoint:CGPointMake(234.6,86.77) controlPoint1: CGPointMake(239.64,85) controlPoint2: CGPointMake(236.94,85.64)];
  [bezierPath2 addCurveToPoint:CGPointMake(233.19,85.76) controlPoint1: CGPointMake(234.15,86.41) controlPoint2: CGPointMake(233.68,86.08)];
  [bezierPath2 closePath];
  [fillColor setFill];
  [bezierPath2 fill];
  
  
  UIBezierPath *bezierPath3 = [UIBezierPath bezierPath];
  
  [bezierPath3 moveToPoint: CGPointMake(102, 270.5)];
  [bezierPath3 addCurveToPoint: CGPointMake(163.5, 207.5) controlPoint1: CGPointMake(121.83, 264.67) controlPoint2: CGPointMake(161.9, 243.9)];
  [bezierPath3 addCurveToPoint: CGPointMake(153.5, 160.5) controlPoint1: CGPointMake(165.1, 171.1) controlPoint2: CGPointMake(157.5, 161)];
  [bezierPath3 moveToPoint: CGPointMake(245.5, 276)];
  [bezierPath3 addCurveToPoint: CGPointMake(192, 247) controlPoint1: CGPointMake(227.17, 275) controlPoint2: CGPointMake(190.8, 267.8)];
  [bezierPath3 addCurveToPoint: CGPointMake(203, 188.5) controlPoint1: CGPointMake(193.2, 226.2) controlPoint2: CGPointMake(199.83, 199.33)];
  [bezierPath3 addCurveToPoint: CGPointMake(212.5, 176.5) controlPoint1: CGPointMake(205.17, 184.17) controlPoint2: CGPointMake(210.1, 175.7)];
  [bezierPath3 moveToPoint: CGPointMake(178.5, 185)];
  [bezierPath3 addCurveToPoint: CGPointMake(171, 234) controlPoint1: CGPointMake(177, 200.17) controlPoint2: CGPointMake(173.4, 231.2)];
  [bezierPath3 moveToPoint: CGPointMake(183.5, 259.5)];
  [bezierPath3 addCurveToPoint: CGPointMake(188.5, 188.5) controlPoint1: CGPointMake(183.5, 251.5) controlPoint2: CGPointMake(182.5, 203)];
  [bezierPath3 moveToPoint: CGPointMake(165, 227.5)];
  [bezierPath3 addCurveToPoint: CGPointMake(144.5, 256.5) controlPoint1: CGPointMake(152, 246.5) controlPoint2: CGPointMake(150.5, 251)];
  
  
  
  //// Bezier 4 Drawing
  UIBezierPath *bezierPath4 = [UIBezierPath bezierPath];
  
  [bezierPath4 moveToPoint: CGPointMake(119.5, 263.5)];
  [bezierPath4 addCurveToPoint: CGPointMake(86, 268.81) controlPoint1: CGPointMake(111.5, 255) controlPoint2: CGPointMake(96.4, 255.61)];
  [bezierPath4 moveToPoint: CGPointMake(59.5, 275)];
  [bezierPath4 addCurveToPoint: CGPointMake(83.5, 268) controlPoint1: CGPointMake(62.83, 271.17) controlPoint2: CGPointMake(72.3, 264.4)];
  [bezierPath4 addCurveToPoint: CGPointMake(94, 272) controlPoint1: CGPointMake(94.7, 271.6) controlPoint2: CGPointMake(95.17, 272.17)];
  [bezierPath4 moveToPoint: CGPointMake(198, 260.5)];
  [bezierPath4 addCurveToPoint: CGPointMake(221.5, 260.5) controlPoint1: CGPointMake(203, 257.73) controlPoint2: CGPointMake(214.7, 253.85)];
  [bezierPath4 addCurveToPoint: CGPointMake(226.74, 266.5) controlPoint1: CGPointMake(223.78, 262.73) controlPoint2: CGPointMake(225.48, 264.74)];
  [bezierPath4 moveToPoint: CGPointMake(230, 273.5)];
  [bezierPath4 addCurveToPoint: CGPointMake(226.74, 266.5) controlPoint1: CGPointMake(230, 272.46) controlPoint2: CGPointMake(229.25, 269.99)];
  [bezierPath4 moveToPoint: CGPointMake(226.74, 266.5)];
  [bezierPath4 addCurveToPoint: CGPointMake(261.5, 268) controlPoint1: CGPointMake(238.33, 263.33) controlPoint2: CGPointMake(261.5, 259.2)];
  [bezierPath4 addCurveToPoint: CGPointMake(244.5, 276) controlPoint1: CGPointMake(261.5, 276.8) controlPoint2: CGPointMake(245.83, 275.17)];
  
  bezierPath4.lineWidth = 0.5;
  bezierPath4.miterLimit = 4;
  bezierPath4.lineCapStyle = kCGLineCapRound;
  
  UIBezierPath *resultPath = [[UIBezierPath alloc] init];
  [resultPath appendPath:bezierPath2];
  [resultPath appendPath:bezierPath3];
  [resultPath appendPath:bezierPath4];
  
  return resultPath;
}

-(UIBezierPath *)drawLandscape {
  // This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
  // http://www.paintcodeapp.com
  
  //// Color Declarations
  UIColor* fillColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
  
  //// landscape-frame.svg Group
  
  //// Rectangle Drawing
  UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(0, 0, 300, 300)];
  [fillColor setFill];
  [rectanglePath fill];
  
  
  //// Bezier Drawing
  UIBezierPath* bezierPath = [UIBezierPath bezierPath];
  [bezierPath moveToPoint: CGPointMake(237.35, 135.88)];
  [bezierPath addLineToPoint: CGPointMake(243.09, 144.26)];
  [bezierPath addLineToPoint: CGPointMake(254.12, 155.29)];
  [bezierPath addLineToPoint: CGPointMake(253.24, 140.74)];
  [bezierPath addLineToPoint: CGPointMake(251.03, 127.06)];
  [bezierPath addLineToPoint: CGPointMake(246.62, 115.15)];
  [bezierPath addLineToPoint: CGPointMake(243.09, 107.65)];
  [bezierPath addLineToPoint: CGPointMake(239.56, 101.03)];
  [bezierPath addLineToPoint: CGPointMake(234.26, 93.53)];
  [bezierPath addLineToPoint: CGPointMake(229.85, 93.09)];
  [bezierPath addLineToPoint: CGPointMake(227.65, 93.09)];
  [bezierPath addLineToPoint: CGPointMake(224.12, 93.53)];
  [bezierPath addLineToPoint: CGPointMake(220.59, 94.85)];
  [bezierPath addLineToPoint: CGPointMake(217.5, 93.09)];
  [bezierPath addLineToPoint: CGPointMake(214.85, 92.21)];
  [bezierPath addLineToPoint: CGPointMake(211.32, 93.09)];
  [bezierPath addLineToPoint: CGPointMake(206.91, 93.09)];
  [bezierPath addLineToPoint: CGPointMake(202.94, 94.85)];
  [bezierPath addLineToPoint: CGPointMake(200.29, 93.53)];
  [bezierPath addLineToPoint: CGPointMake(196.76, 92.21)];
  [bezierPath addLineToPoint: CGPointMake(193.24, 92.21)];
  [bezierPath addLineToPoint: CGPointMake(187.06, 92.21)];
  [bezierPath addLineToPoint: CGPointMake(181.32, 92.21)];
  [bezierPath addLineToPoint: CGPointMake(178.68, 93.53)];
  [bezierPath addLineToPoint: CGPointMake(172.94, 92.21)];
  [bezierPath addLineToPoint: CGPointMake(167.65, 92.21)];
  [bezierPath addLineToPoint: CGPointMake(164.12, 91.32)];
  [bezierPath addLineToPoint: CGPointMake(159.26, 93.09)];
  [bezierPath addLineToPoint: CGPointMake(156.18, 91.32)];
  [bezierPath addLineToPoint: CGPointMake(150, 91.32)];
  [bezierPath addLineToPoint: CGPointMake(154.85, 90)];
  [bezierPath addLineToPoint: CGPointMake(157.94, 87.35)];
  [bezierPath addLineToPoint: CGPointMake(159.26, 85.59)];
  [bezierPath addLineToPoint: CGPointMake(161.91, 83.38)];
  [bezierPath addLineToPoint: CGPointMake(164.12, 80.29)];
  [bezierPath addLineToPoint: CGPointMake(167.65, 80.29)];
  [bezierPath addLineToPoint: CGPointMake(174.26, 80.29)];
  [bezierPath addLineToPoint: CGPointMake(179.12, 80.29)];
  [bezierPath addLineToPoint: CGPointMake(183.53, 77.65)];
  [bezierPath addLineToPoint: CGPointMake(185.29, 74.12)];
  [bezierPath addLineToPoint: CGPointMake(191.03, 73.24)];
  [bezierPath addLineToPoint: CGPointMake(194.12, 75.44)];
  [bezierPath addLineToPoint: CGPointMake(197.65, 74.12)];
  [bezierPath addLineToPoint: CGPointMake(201.18, 75.44)];
  [bezierPath addLineToPoint: CGPointMake(202.94, 71.91)];
  [bezierPath addLineToPoint: CGPointMake(206.91, 70.15)];
  [bezierPath addLineToPoint: CGPointMake(212.21, 70.15)];
  [bezierPath addLineToPoint: CGPointMake(202.94, 63.53)];
  [bezierPath addLineToPoint: CGPointMake(191.03, 56.91)];
  [bezierPath addLineToPoint: CGPointMake(175.59, 50.74)];
  [bezierPath addLineToPoint: CGPointMake(157.94, 47.21)];
  [bezierPath addLineToPoint: CGPointMake(144.26, 46.32)];
  [bezierPath addLineToPoint: CGPointMake(129.26, 47.21)];
  [bezierPath addLineToPoint: CGPointMake(114.71, 49.41)];
  [bezierPath addLineToPoint: CGPointMake(103.24, 53.82)];
  [bezierPath addLineToPoint: CGPointMake(93.09, 58.24)];
  [bezierPath addLineToPoint: CGPointMake(97.94, 60.88)];
  [bezierPath addLineToPoint: CGPointMake(101.47, 64.41)];
  [bezierPath addLineToPoint: CGPointMake(104.12, 69.26)];
  [bezierPath addLineToPoint: CGPointMake(104.56, 74.12)];
  [bezierPath addLineToPoint: CGPointMake(101.47, 81.18)];
  [bezierPath addLineToPoint: CGPointMake(96.62, 85.59)];
  [bezierPath addLineToPoint: CGPointMake(93.09, 87.35)];
  [bezierPath addLineToPoint: CGPointMake(89.12, 87.35)];
  [bezierPath addLineToPoint: CGPointMake(82.94, 84.71)];
  [bezierPath addLineToPoint: CGPointMake(78.53, 81.18)];
  [bezierPath addLineToPoint: CGPointMake(75.44, 75.44)];
  [bezierPath addLineToPoint: CGPointMake(75.44, 70.15)];
  [bezierPath addLineToPoint: CGPointMake(64.41, 79.85)];
  [bezierPath addLineToPoint: CGPointMake(56.91, 88.68)];
  [bezierPath addLineToPoint: CGPointMake(50.29, 98.82)];
  [bezierPath addLineToPoint: CGPointMake(45.44, 108.53)];
  [bezierPath addLineToPoint: CGPointMake(44.12, 113.82)];
  [bezierPath addLineToPoint: CGPointMake(47.21, 113.82)];
  [bezierPath addLineToPoint: CGPointMake(50.29, 112.94)];
  [bezierPath addLineToPoint: CGPointMake(56.03, 116.47)];
  [bezierPath addLineToPoint: CGPointMake(61.32, 116.47)];
  [bezierPath addLineToPoint: CGPointMake(66.62, 120.88)];
  [bezierPath addLineToPoint: CGPointMake(69.71, 120)];
  [bezierPath addLineToPoint: CGPointMake(74.12, 122.21)];
  [bezierPath addLineToPoint: CGPointMake(71.91, 123.09)];
  [bezierPath addLineToPoint: CGPointMake(66.62, 124.41)];
  [bezierPath addLineToPoint: CGPointMake(62.21, 123.53)];
  [bezierPath addLineToPoint: CGPointMake(60.44, 124.41)];
  [bezierPath addLineToPoint: CGPointMake(56.91, 124.41)];
  [bezierPath addLineToPoint: CGPointMake(54.26, 124.41)];
  [bezierPath addLineToPoint: CGPointMake(52.5, 126.18)];
  [bezierPath addLineToPoint: CGPointMake(50.74, 125.29)];
  [bezierPath addLineToPoint: CGPointMake(48.97, 125.29)];
  [bezierPath addLineToPoint: CGPointMake(44.12, 123.09)];
  [bezierPath addLineToPoint: CGPointMake(39.26, 125.29)];
  [bezierPath addLineToPoint: CGPointMake(37.06, 132.79)];
  [bezierPath addLineToPoint: CGPointMake(35.29, 155.74)];
  [bezierPath addLineToPoint: CGPointMake(39.26, 182.21)];
  [bezierPath addLineToPoint: CGPointMake(45.44, 176.03)];
  [bezierPath addLineToPoint: CGPointMake(50.29, 172.5)];
  [bezierPath addLineToPoint: CGPointMake(60.44, 161.47)];
  [bezierPath addLineToPoint: CGPointMake(69.71, 151.32)];
  [bezierPath moveToPoint: CGPointMake(237.35, 135.88)];
  [bezierPath addLineToPoint: CGPointMake(227.65, 140.74)];
  [bezierPath moveToPoint: CGPointMake(237.35, 135.88)];
  [bezierPath addLineToPoint: CGPointMake(235.74, 144.26)];
  [bezierPath addLineToPoint: CGPointMake(235.74, 154.41)];
  [bezierPath moveToPoint: CGPointMake(227.65, 140.74)];
  [bezierPath addLineToPoint: CGPointMake(217.5, 120)];
  [bezierPath addLineToPoint: CGPointMake(210, 113.38)];
  [bezierPath addLineToPoint: CGPointMake(202.94, 122.21)];
  [bezierPath addLineToPoint: CGPointMake(193.24, 133.24)];
  [bezierPath addLineToPoint: CGPointMake(189.26, 131.03)];
  [bezierPath addLineToPoint: CGPointMake(174.26, 146.91)];
  [bezierPath addLineToPoint: CGPointMake(161.91, 165)];
  [bezierPath moveToPoint: CGPointMake(227.65, 140.74)];
  [bezierPath addLineToPoint: CGPointMake(231.18, 146.91)];
  [bezierPath addLineToPoint: CGPointMake(235.74, 154.41)];
  [bezierPath moveToPoint: CGPointMake(161.91, 165)];
  [bezierPath addLineToPoint: CGPointMake(154.85, 157.06)];
  [bezierPath addLineToPoint: CGPointMake(136.76, 139.41)];
  [bezierPath addLineToPoint: CGPointMake(130.15, 122.21)];
  [bezierPath addLineToPoint: CGPointMake(126.18, 122.21)];
  [bezierPath addLineToPoint: CGPointMake(120.44, 113.38)];
  [bezierPath moveToPoint: CGPointMake(161.91, 165)];
  [bezierPath addLineToPoint: CGPointMake(161.91, 167.21)];
  [bezierPath addLineToPoint: CGPointMake(165, 170.29)];
  [bezierPath addLineToPoint: CGPointMake(171.4, 176.69)];
  [bezierPath moveToPoint: CGPointMake(120.44, 113.38)];
  [bezierPath addLineToPoint: CGPointMake(110.29, 120.88)];
  [bezierPath addLineToPoint: CGPointMake(107.21, 127.06)];
  [bezierPath addLineToPoint: CGPointMake(97.5, 138.09)];
  [bezierPath addLineToPoint: CGPointMake(92.21, 135.88)];
  [bezierPath moveToPoint: CGPointMake(120.44, 113.38)];
  [bezierPath addLineToPoint: CGPointMake(116.91, 120)];
  [bezierPath addLineToPoint: CGPointMake(115.59, 127.06)];
  [bezierPath moveToPoint: CGPointMake(92.21, 135.88)];
  [bezierPath addLineToPoint: CGPointMake(78.53, 153.53)];
  [bezierPath addLineToPoint: CGPointMake(69.71, 151.32)];
  [bezierPath moveToPoint: CGPointMake(92.21, 135.88)];
  [bezierPath addLineToPoint: CGPointMake(92.21, 146.91)];
  [bezierPath addLineToPoint: CGPointMake(93.97, 157.06)];
  [bezierPath moveToPoint: CGPointMake(69.71, 151.32)];
  [bezierPath addLineToPoint: CGPointMake(72.79, 156.62)];
  [bezierPath addLineToPoint: CGPointMake(74.12, 162.79)];
  [bezierPath addLineToPoint: CGPointMake(74.12, 171.18)];
  [bezierPath addLineToPoint: CGPointMake(78.53, 179.56)];
  [bezierPath moveToPoint: CGPointMake(177.79, 183.09)];
  [bezierPath addLineToPoint: CGPointMake(171.4, 176.69)];
  [bezierPath moveToPoint: CGPointMake(245.74, 172.06)];
  [bezierPath addLineToPoint: CGPointMake(237.35, 157.06)];
  [bezierPath addLineToPoint: CGPointMake(235.74, 154.41)];
  [bezierPath moveToPoint: CGPointMake(171.4, 176.69)];
  [bezierPath addLineToPoint: CGPointMake(183.53, 172.5)];
  [bezierPath addLineToPoint: CGPointMake(184.55, 173.82)];
  [bezierPath moveToPoint: CGPointMake(191.03, 182.21)];
  [bezierPath addLineToPoint: CGPointMake(184.55, 173.82)];
  [bezierPath moveToPoint: CGPointMake(184.55, 173.82)];
  [bezierPath addLineToPoint: CGPointMake(191.03, 171.18)];
  [bezierPath addLineToPoint: CGPointMake(196.76, 173.82)];
  [bezierPath addLineToPoint: CGPointMake(205.59, 179.56)];
  [bezierPath addLineToPoint: CGPointMake(214.85, 183.09)];
  [bezierPath addLineToPoint: CGPointMake(222.35, 189.26)];
  [bezierPath addLineToPoint: CGPointMake(227.65, 190.59)];
  [bezierPath addLineToPoint: CGPointMake(241.32, 201.18)];
  [bezierPath moveToPoint: CGPointMake(112.94, 149.12)];
  [bezierPath addLineToPoint: CGPointMake(112.94, 141.62)];
  [bezierPath addLineToPoint: CGPointMake(114.26, 133.24)];
  bezierPath.lineWidth = 1;
  bezierPath.miterLimit = 4;
  bezierPath.lineCapStyle = kCGLineCapRound;
  
  
  //// Bezier 2 Drawing
  UIBezierPath* bezier2Path = [UIBezierPath bezierPath];
  [bezier2Path moveToPoint: CGPointMake(48.97, 206.03)];
  [bezier2Path addLineToPoint: CGPointMake(61.76, 206.03)];
  [bezier2Path addLineToPoint: CGPointMake(74.12, 202.94)];
  [bezier2Path addLineToPoint: CGPointMake(89.56, 194.56)];
  [bezier2Path addLineToPoint: CGPointMake(104.56, 190.15)];
  [bezier2Path addLineToPoint: CGPointMake(118.68, 195.88)];
  [bezier2Path addLineToPoint: CGPointMake(129.93, 200.96)];
  [bezier2Path moveToPoint: CGPointMake(141.18, 206.03)];
  [bezier2Path addLineToPoint: CGPointMake(129.93, 200.96)];
  [bezier2Path moveToPoint: CGPointMake(129.93, 200.96)];
  [bezier2Path addLineToPoint: CGPointMake(141.18, 197.65)];
  [bezier2Path addLineToPoint: CGPointMake(150, 198.97)];
  [bezier2Path addLineToPoint: CGPointMake(158.38, 200.96)];
  [bezier2Path addLineToPoint: CGPointMake(170.29, 202.94)];
  [bezier2Path addLineToPoint: CGPointMake(189.71, 209.56)];
  [bezier2Path moveToPoint: CGPointMake(181.32, 211.76)];
  [bezier2Path addLineToPoint: CGPointMake(192.35, 209.56)];
  [bezier2Path addLineToPoint: CGPointMake(201.62, 204.71)];
  [bezier2Path addLineToPoint: CGPointMake(213.97, 204.71)];
  [bezier2Path addLineToPoint: CGPointMake(226.76, 204.71)];
  [bezier2Path addLineToPoint: CGPointMake(244.41, 200.96)];
  [bezier2Path moveToPoint: CGPointMake(67.5, 230.74)];
  [bezier2Path addLineToPoint: CGPointMake(79.85, 230.74)];
  [bezier2Path addLineToPoint: CGPointMake(94.85, 227.65)];
  [bezier2Path addLineToPoint: CGPointMake(109.85, 230.74)];
  [bezier2Path addLineToPoint: CGPointMake(131.47, 233.38)];
  [bezier2Path addLineToPoint: CGPointMake(170.29, 237.35)];
  [bezier2Path moveToPoint: CGPointMake(141.18, 245.74)];
  [bezier2Path addLineToPoint: CGPointMake(161.91, 240.44)];
  [bezier2Path addLineToPoint: CGPointMake(181.32, 230.74)];
  [bezier2Path addLineToPoint: CGPointMake(192.35, 225)];
  [bezier2Path addLineToPoint: CGPointMake(208.68, 225)];
  [bezier2Path addLineToPoint: CGPointMake(228.09, 225)];
  [bezier2Path moveToPoint: CGPointMake(93.53, 251.47)];
  [bezier2Path addLineToPoint: CGPointMake(104.56, 249.26)];
  [bezier2Path addLineToPoint: CGPointMake(126.18, 251.47)];
  [bezier2Path addLineToPoint: CGPointMake(150.88, 252.35)];
  [bezier2Path addLineToPoint: CGPointMake(170.29, 252.35)];
  [bezier2Path addLineToPoint: CGPointMake(189.71, 245.74)];
  [bezier2Path addLineToPoint: CGPointMake(210, 243.53)];
  bezier2Path.lineWidth = 1;
  bezier2Path.miterLimit = 4;
  bezier2Path.lineCapStyle = kCGLineCapRound;
  
  
  //// Bezier 3 Drawing
  UIBezierPath* bezier3Path = [UIBezierPath bezierPath];
  [bezier3Path moveToPoint: CGPointMake(108.97, 152.65)];
  [bezier3Path addLineToPoint: CGPointMake(110.74, 158.38)];
  [bezier3Path addLineToPoint: CGPointMake(111.62, 168.09)];
  [bezier3Path addLineToPoint: CGPointMake(109.41, 184.41)];
  [bezier3Path addLineToPoint: CGPointMake(106.32, 199.85)];
  [bezier3Path addLineToPoint: CGPointMake(106.76, 208.24)];
  [bezier3Path addLineToPoint: CGPointMake(109.41, 215.29)];
  [bezier3Path moveToPoint: CGPointMake(113.38, 215.29)];
  [bezier3Path addLineToPoint: CGPointMake(114.26, 205.15)];
  [bezier3Path moveToPoint: CGPointMake(115.15, 201.62)];
  [bezier3Path addLineToPoint: CGPointMake(114.26, 191.03)];
  [bezier3Path addLineToPoint: CGPointMake(113.38, 183.97)];
  [bezier3Path addLineToPoint: CGPointMake(112.5, 177.35)];
  [bezier3Path moveToPoint: CGPointMake(120, 172.5)];
  [bezier3Path addLineToPoint: CGPointMake(121.76, 179.56)];
  [bezier3Path addLineToPoint: CGPointMake(123.09, 188.82)];
  [bezier3Path moveToPoint: CGPointMake(124.41, 180.44)];
  [bezier3Path addLineToPoint: CGPointMake(124.85, 185.74)];
  [bezier3Path addLineToPoint: CGPointMake(127.06, 193.68)];
  [bezier3Path addLineToPoint: CGPointMake(129.26, 198.97)];
  [bezier3Path moveToPoint: CGPointMake(127.94, 188.82)];
  [bezier3Path addLineToPoint: CGPointMake(128.38, 192.79)];
  [bezier3Path addLineToPoint: CGPointMake(131.47, 198.09)];
  [bezier3Path moveToPoint: CGPointMake(139.41, 178.24)];
  [bezier3Path addLineToPoint: CGPointMake(140.29, 184.41)];
  [bezier3Path addLineToPoint: CGPointMake(141.62, 190.59)];
  [bezier3Path addLineToPoint: CGPointMake(143.82, 195.44)];
  [bezier3Path moveToPoint: CGPointMake(146.91, 196.76)];
  [bezier3Path addLineToPoint: CGPointMake(144.26, 191.47)];
  [bezier3Path addLineToPoint: CGPointMake(142.94, 187.06)];
  [bezier3Path addLineToPoint: CGPointMake(142.5, 182.65)];
  [bezier3Path moveToPoint: CGPointMake(140.29, 190.59)];
  [bezier3Path addLineToPoint: CGPointMake(138.53, 185.29)];
  [bezier3Path addLineToPoint: CGPointMake(137.65, 180)];
  [bezier3Path addLineToPoint: CGPointMake(137.21, 172.94)];
  [bezier3Path addLineToPoint: CGPointMake(137.65, 166.76)];
  [bezier3Path moveToPoint: CGPointMake(87.35, 157.5)];
  [bezier3Path addLineToPoint: CGPointMake(85.15, 164.12)];
  [bezier3Path addLineToPoint: CGPointMake(84.26, 170.29)];
  [bezier3Path addLineToPoint: CGPointMake(84.26, 177.35)];
  [bezier3Path moveToPoint: CGPointMake(82.5, 172.5)];
  [bezier3Path addLineToPoint: CGPointMake(82.94, 165.44)];
  [bezier3Path addLineToPoint: CGPointMake(85.15, 157.5)];
  [bezier3Path addLineToPoint: CGPointMake(88.24, 150.88)];
  [bezier3Path moveToPoint: CGPointMake(90.44, 141.18)];
  [bezier3Path addLineToPoint: CGPointMake(86.91, 146.47)];
  [bezier3Path addLineToPoint: CGPointMake(84.26, 151.76)];
  [bezier3Path moveToPoint: CGPointMake(51.62, 177.35)];
  [bezier3Path addLineToPoint: CGPointMake(49.85, 184.41)];
  [bezier3Path addLineToPoint: CGPointMake(47.21, 191.03)];
  [bezier3Path addLineToPoint: CGPointMake(44.56, 195.88)];
  [bezier3Path moveToPoint: CGPointMake(54.26, 177.35)];
  [bezier3Path addLineToPoint: CGPointMake(52.5, 183.97)];
  [bezier3Path addLineToPoint: CGPointMake(49.41, 191.91)];
  [bezier3Path moveToPoint: CGPointMake(55.59, 170.29)];
  [bezier3Path addLineToPoint: CGPointMake(54.71, 175.15)];
  [bezier3Path moveToPoint: CGPointMake(67.5, 158.38)];
  [bezier3Path addLineToPoint: CGPointMake(65.29, 166.76)];
  [bezier3Path moveToPoint: CGPointMake(66.62, 169.41)];
  [bezier3Path addLineToPoint: CGPointMake(65.29, 175.15)];
  [bezier3Path addLineToPoint: CGPointMake(64.85, 181.76)];
  [bezier3Path moveToPoint: CGPointMake(63.97, 171.62)];
  [bezier3Path addLineToPoint: CGPointMake(63.09, 180)];
  [bezier3Path moveToPoint: CGPointMake(72.79, 182.65)];
  [bezier3Path addLineToPoint: CGPointMake(73.24, 187.94)];
  [bezier3Path moveToPoint: CGPointMake(74.56, 188.82)];
  [bezier3Path addLineToPoint: CGPointMake(74.56, 201.62)];
  [bezier3Path moveToPoint: CGPointMake(88.24, 171.62)];
  [bezier3Path addLineToPoint: CGPointMake(88.68, 181.32)];
  [bezier3Path addLineToPoint: CGPointMake(89.56, 188.82)];
  [bezier3Path moveToPoint: CGPointMake(186.62, 142.06)];
  [bezier3Path addLineToPoint: CGPointMake(187.06, 146.03)];
  [bezier3Path addLineToPoint: CGPointMake(189.26, 151.76)];
  [bezier3Path addLineToPoint: CGPointMake(189.74, 153.97)];
  [bezier3Path moveToPoint: CGPointMake(189.26, 164.56)];
  [bezier3Path addLineToPoint: CGPointMake(190.59, 157.94)];
  [bezier3Path addLineToPoint: CGPointMake(189.74, 153.97)];
  [bezier3Path moveToPoint: CGPointMake(190.59, 141.62)];
  [bezier3Path addLineToPoint: CGPointMake(190.15, 146.91)];
  [bezier3Path addLineToPoint: CGPointMake(189.74, 153.97)];
  [bezier3Path moveToPoint: CGPointMake(200.74, 135.44)];
  [bezier3Path addLineToPoint: CGPointMake(198.97, 142.06)];
  [bezier3Path addLineToPoint: CGPointMake(197.21, 148.68)];
  [bezier3Path moveToPoint: CGPointMake(217.06, 144.71)];
  [bezier3Path addLineToPoint: CGPointMake(218.38, 153.09)];
  [bezier3Path addLineToPoint: CGPointMake(223.68, 164.56)];
  [bezier3Path moveToPoint: CGPointMake(198.97, 183.97)];
  [bezier3Path addLineToPoint: CGPointMake(202.94, 190.59)];
  [bezier3Path addLineToPoint: CGPointMake(207.35, 195.44)];
  [bezier3Path moveToPoint: CGPointMake(197.21, 195.88)];
  [bezier3Path addLineToPoint: CGPointMake(192.35, 192.79)];
  [bezier3Path moveToPoint: CGPointMake(241.32, 150.88)];
  [bezier3Path addLineToPoint: CGPointMake(241.32, 153.97)];
  [bezier3Path moveToPoint: CGPointMake(245.29, 153.09)];
  [bezier3Path addLineToPoint: CGPointMake(245.29, 157.5)];
  [bezier3Path addLineToPoint: CGPointMake(247.5, 161.03)];
  [bezier3Path moveToPoint: CGPointMake(123.09, 137.65)];
  [bezier3Path addLineToPoint: CGPointMake(124.85, 146.03)];
  [bezier3Path addLineToPoint: CGPointMake(129.26, 148.68)];
  [bezier3Path addLineToPoint: CGPointMake(131.47, 153.97)];
  [bezier3Path moveToPoint: CGPointMake(210.88, 120.44)];
  [bezier3Path addLineToPoint: CGPointMake(212.65, 123.53)];
  [bezier3Path addLineToPoint: CGPointMake(212.65, 127.06)];
  [bezier3Path moveToPoint: CGPointMake(207.35, 125.74)];
  [bezier3Path addLineToPoint: CGPointMake(206.03, 134.56)];
  [bezier3Path moveToPoint: CGPointMake(214.85, 190.59)];
  [bezier3Path addLineToPoint: CGPointMake(217.06, 191.91)];
  [bezier3Path addLineToPoint: CGPointMake(221.47, 193.68)];
  [bezier3Path addLineToPoint: CGPointMake(228.97, 199.85)];
  [bezier3Path moveToPoint: CGPointMake(158.38, 171.62)];
  [bezier3Path addLineToPoint: CGPointMake(160.59, 177.35)];
  [bezier3Path addLineToPoint: CGPointMake(166.32, 183.97)];
  bezier3Path.lineWidth = 0.5;
  bezier3Path.miterLimit = 4;
  bezier3Path.lineCapStyle = kCGLineCapRound;
  
  UIBezierPath *resultPath = [[UIBezierPath alloc] init];
  [resultPath appendPath:bezierPath];
  [resultPath appendPath:bezier2Path];
  [resultPath appendPath:bezier3Path];
  
  return resultPath;
}

@end
